server:
  port: 9093

spring:
  thymeleaf:
    cache: false
    mode: HTML5
    suffix: .html
    prefix: classpath:/templates/
  servlet:
    multipart:
      enable: true
  http:
    multipart:
      enabled: true
      max-file-size: 500000KB
      max-request-size: 500000KB
  

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

